/** @type {import('tailwindcss').Config} */
// Design tokens ported verbatim from the Stitch "Radical Precision" (Neobrutalist)
// design system for the JobSpy Neobrutalist UI project.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#670020",
        "outline-variant": "#3a4a49",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#00fbfb",
        "on-surface-variant": "#b9cac9",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#abd600",
        "primary-fixed-dim": "#00dddd",
        "tertiary-fixed": "#ffd9dc",
        "on-primary-container": "#007070",
        "on-primary": "#003737",
        secondary: "#ffffff",
        "on-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#004f4f",
        "on-tertiary-fixed-variant": "#910030",
        error: "#ffb4ab",
        "on-secondary": "#283500",
        tertiary: "#ffffff",
        "secondary-fixed": "#c3f400",
        "on-background": "#e5e2e1",
        "on-primary-fixed": "#002020",
        "on-error": "#690005",
        "tertiary-container": "#ffd9dc",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#c3f400",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#c90046",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#006a6a",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#3c4d00",
        "surface-bright": "#3a3939",
        "primary-container": "#00fbfb",
        "on-secondary-fixed": "#161e00",
        "surface-tint": "#00dddd",
        "on-tertiary-fixed": "#400011",
        primary: "#ffffff",
        "surface-variant": "#353534",
        surface: "#131313",
        outline: "#839493",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        background: "#131313",
        // The deep "void" base used as the page canvas (from override-neutral).
        void: "#0a0a0a",
        // Functional accent aliases from the design brief.
        "accent-cyan": "#00ffff",
        "accent-lime": "#ccff00",
        "accent-pink": "#ff3366",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "border-thin": "2px",
        "margin-page": "32px",
        "border-thick": "4px",
        "shadow-offset-sm": "4px",
        "shadow-offset-lg": "8px",
        gutter: "24px",
      },
      borderWidth: {
        DEFAULT: "2px",
        thin: "2px",
        thick: "4px",
        "border-thin": "2px",
        "border-thick": "4px",
      },
      fontFamily: {
        sans: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "meta-sm": ["JetBrains Mono"],
        "meta-xs": ["JetBrains Mono"],
        "headline-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
        "body-md": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
      },
      fontSize: {
        "meta-sm": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "meta-xs": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
